#!/data/data/com.termux/files/usr/bin/env bash
#
# EXT
set -e

pacman -Syyu --noconfirm
pacman -S zsh{,-completions} micro --noconfirm
pacman -Rddn command-not-found --noconfirm

id="$(id -u)"
bsdtar --uid "${id}" --gid "${id}" -x -f "${PREFIX}/tmp/cfg.tar" -C "${PREFIX%/*}"

chsh -s zsh
rm -rf "${PREFIX}/etc/termux"
echo > "${PREFIX}/etc/motd"
