#!/system/bin/env sh
#
# Setup pacman in termux
set -e

bootstrap="${HOME}/bootstrap"
tmp="${PREFIX}/tmp/tqs"
url="https://github.com/nedorazrab0/tqs/releases/download/tqs/tqs.tar.lz4"

# Check failsafe
if [ -n "${TERMUX_MAIN_PACKAGE_FORMAT}" ]; then
  echo
  echo '! Not failsafe'
  echo '- Left edge swipe ==> "new session" (long-tap)'
  exit 1
fi

# Main
[ -d "${bootstrap}" ] && rm -rf "${bootstrap}"
mkdir -p "${bootstrap}"

if [ "$(uname -m)" == 'aarch64' ]; then
  arch='aarch64'
else
  arch='arm'
fi

"${PREFIX}/bin/curl" -fLZ "https://github.com/termux-pacman/termux-packages/\
releases/latest/download/bootstrap-${arch}.zip" \
  -o "${PREFIX}/bootstrap.zip"

unzip "${PREFIX}/bootstrap.zip" -d "${bootstrap}"
cd "${bootstrap}"  # For symlinks
awk -F '←' \
  '{system("ln -sv '"'"'"$1"'"'"' '"'"'"$2"'"'"' &")}' \
  "${bootstrap}/SYMLINKS.txt"

rm -f "${bootstrap}/SYMLINKS.txt"
rm -rf "${PREFIX}"
cd ..
mv "${bootstrap}" "${PREFIX}"

# Use new bootstrap
export PATH="${PREFIX}/bin"

# Configs
curl -fL "https://raw.githubusercontent.com/nedorazrab0/tqs/refs/heads/main/\
cfg/usr/etc/pacman.conf" -o "${PREFIX}/etc/pacman.conf"

pacman-key --init
pacman-key --populate
pacman -Syyu lz4 bsdtar --noconfirm

rm -rf "${HOME}/"*

[ -d "${tmp}" ] && rm -rf "${tmp}"
mkdir -p "${tmp}"
curl -fL "${url}" | lz4 -dvc | bsdtar -x -C "${tmp}"

exec bash "${tmp}/ext"
